### PR TITLE
Update to use new cyBQMs

### PR DESCRIPTION
**Pull request by arcondello**
To allow Tabu to use the new cyBQMs added in https://github.com/dwavesystems/dimod/pull/533, note that some more changes will be required, specifically to handle the `bqm.to_numpy_matrix` call, see https://github.com/dwavesystems/dwave-tabu/blob/fa71bbbae920212edec6beeaa99bfbc98eb45368/tabu/sampler.py#L225

### CODE REVIEW

**Comment by randomir** [comment]
@arcondello, what's blocking this? Would you like me to take a crack at this?

**Comment by arcondello** [comment]
I was waiting for https://github.com/dwavesystems/dimod/pull/644 to be deployed. But I can finish this work and do the initial_states stuff as a second PR.

**Comment by randomir** [comment]
Since initial states work is unrelated to cybqm support, I'd vote for a second PR.

**Comment by arcondello** [comment]
They are not unrelated. Because cyBQMs also introduce variable ordering and "true" cybqm support means pulling the BQM-to-[BQP](https://github.com/dwavesystems/dwave-tabu/blob/aa5cbb2040e92da419b7ade786ad02385e6d9450/tabu/src/bqpUtil.h#L34) into C space. But for now I can make an, ultimately redundant, pass through `BQM.to_numpy_vectors` to get it working.

**Comment by randomir** [comment]
Ok, I didn't realize `to_numpy_vectors` needs to be tweaked for this. Why `to_numpy_matrix` can't be used (until we implement that "true" support/conversion)?

I'm not trying to say we should do redundant work, just trying to see what's the minimum we need to do here to make dwave-tabu ocean2-compatible.

**Comment by arcondello** [comment]
Well, it turns out that we had some bugs anyway. The main one is that BQMs with labels of different types fail, even for legacy BQMs.
```
bqm = dimod.BQM.from_ising({'a': 0, 1: 1}, {})
tabu.TabuSampler().sample(bqm)
```
Side note, @wbernoudy's suggestion that led to https://github.com/dwavesystems/dimod/pull/627 was an excellent one.

**Comment by randomir** [comment]
Re: side note, I missed https://github.com/dwavesystems/dimod/pull/627. Great feature! I had to reimplement similar tests on too many occasions.

**Comment by arcondello** [comment]
Ok, this should unblock things for now. However, it still casts the BQM to a dense matrix (in python lists!). We'll definitely want to change that in the long run.

**Comment by randomir** [comment]
(the cpp-tests should be fixed if you rebase)

**Comment by randomir** [comment]
Oh, and re: dense matrix, I agree -- but that will require C code refactor; probably not trivial.

**Pull request merged**
